version: '2.2'

services:
    bemodule:
      container_name: budgetcontrol-ms-authentication
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8083:80"
      restart: unless-stopped

networks:
  budgetcontrol_network:
    external: false
    name: budgetcontrol_network

volumes:
  mysql_persistent:
    name: budgetcontrol_core_database
    external: true