version: '3'
dotenv:
  - ".env"
tasks:
  build:dev:
    desc: Build dev enviroment
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.db.yml up -d
      - docker container cp bin/apache/default.conf budgetcontrol-ms-authentication:/etc/apache2/sites-available/budgetcontrol.cloud.conf
      - docker container exec budgetcontrol-ms-authentication service apache2 restart
